# Generated by Django 4.2.5 on 2023-09-07 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloodrequest',
            old_name='condition',
            new_name='patient_condition',
        ),
    ]
